model:
  model_name: "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct"
  trust_remote_code: true
  torch_dtype_str: "float16"
  model_max_length: 4096

data:
  train:
    datasets:
      - dataset_name: "HuggingFaceH4/CodeAlpaca-20k"
        split: "train"

training:
  output_dir: "output/code-gen-model"
  trainer_type: "TRL_SFT"
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8
  learning_rate: 2e-5
  max_steps: 800
  optimizer: "adamw_torch_fused"
  seed: 42
  use_peft: True

peft:
  lora_r: 64
  lora_alpha: 128
  lora_target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
