id: security-scan-flow
namespace: company.team

description: Automated security scanning workflow with AI-powered fixes

inputs:
  - id: scanId
    type: STRING
    description: Unique scan identifier
  - id: repoUrl
    type: STRING
    description: GitHub repository URL
  - id: branch
    type: STRING
    description: Branch to scan
    defaults: main
  - id: backendUrl
    type: STRING
    description: Backend API URL for callbacks

variables:
  fixBranch: "security-fixes-{{execution.startDate | date('yyyyMMdd-HHmmss')}}"

tasks:
  # Step 1: Clone Repository and Run Scans
  - id: clone_and_scan
    type: io.kestra.plugin.scripts.shell.Commands
    description: Clone repository and run security scans
    outputFiles:
      - "semgrep-results.json"
      - "eslint-results.json"
      - "bandit-results.json"
      - "gitleaks-results.json"
    commands:
      - |
        echo "Cloning repository..."
        git clone -b {{inputs.branch}} https://{{secret('GITHUB_TOKEN')}}@{{inputs.repoUrl | replace('https://', '')}} repo
        cd repo
        
        echo "Repository cloned successfully"
        ls -la
        
        echo "Installing dependencies if needed..."
        if [ -f "package.json" ]; then
          echo "Found package.json, installing npm dependencies..."
          npm install --production || echo "npm install failed or not available"
        fi
        
        if [ -f "requirements.txt" ]; then
          echo "Found requirements.txt, installing pip dependencies..."
          pip install -r requirements.txt || echo "pip install failed or not available"
        fi
        
        echo "Running security scans..."
        
        # Run Semgrep
        echo "Running Semgrep..."
        semgrep --config auto --json -o ../semgrep-results.json . || echo "Semgrep scan completed with issues or tool not available"
        
        # Run ESLint
        echo "Running ESLint..."
        eslint . --format json -o ../eslint-results.json || echo "ESLint scan completed with issues or tool not available"
        
        # Run Bandit
        echo "Running Bandit..."
        bandit -r . -f json -o ../bandit-results.json || echo "Bandit scan completed with issues or tool not available"
        
        # Run Gitleaks
        echo "Running Gitleaks..."
        gitleaks detect --report-format json --report-path ../gitleaks-results.json || echo "Gitleaks scan completed with issues or tool not available"
        
        echo "All scans completed!"
        cd ..
        ls -la

  # Step 2: Aggregate Results
  - id: aggregate_results
    type: io.kestra.plugin.scripts.python.Commands
    description: Aggregate and normalize all scan results
    outputFiles:
      - "aggregated-results.json"
    commands:
      - |
        import json
        import os
        
        results = []
        
        # Load all result files from working directory
        tools = ['semgrep', 'eslint', 'bandit', 'gitleaks']
        for tool in tools:
            filepath = f'{tool}-results.json'
            if os.path.exists(filepath):
                try:
                    with open(filepath, 'r') as f:
                        data = json.load(f)
                        results.append({'tool': tool, 'data': data})
                except Exception as e:
                    print(f"Error loading {tool} results: {e}")
        
        # 1. Save file locally
        with open('aggregated-results.json', 'w') as f:
            json.dump(results, f, indent=2)
        
        # 2. Output Vars
        total_count = len(results)
        print(f'::{{ "outputs": {{ "findings": {json.dumps(results)}, "total_findings": {total_count} }} }}::')

  # Step 5: AI Fix Generation Loop
  - id: generate_fixes
    type: io.kestra.plugin.core.flow.ForEach
    description: Generate AI fixes for each finding
    values: "{{outputs.aggregate_results.findings}}"
    concurrencyLimit: 5
    tasks:
      - id: fix_issue
        type: io.kestra.plugin.scripts.shell.Commands
        description: Call backend API to generate fix
        commands:
          - |
            curl -X POST {{inputs.backendUrl}}/api/scan/fix \
              -H "Content-Type: application/json" \
              -d '{
                "scanId": "{{inputs.scanId}}",
                "finding": {{taskrun.value}},
                "fileContent": "$(cat {{vars.repoDir}}/{{taskrun.value.file}})"
              }' \
              -o fix-result.json

  # Step 6: Create Branch and Commit
  - id: commit_fixes
    type: io.kestra.plugin.scripts.shell.Commands
    description: Create branch and commit all fixes
    commands:
      - cd {{vars.repoDir}}
      - git config user.email "security-bot@company.com"
      - git config user.name "Security Bot"
      - git checkout -b {{vars.fixBranch}}
      - git add .
      - |
        git commit -m "🔒 Security fixes - Automated scan {{inputs.scanId}}
        
        Applied automated security fixes for vulnerabilities detected by:
        - Semgrep
        - ESLint
        - Bandit
        - Gitleaks
        
        Scan ID: {{inputs.scanId}}
        Generated: {{execution.startDate}}"

  # Step 7: Push Branch
  - id: push_branch
    type: io.kestra.plugin.scripts.shell.Commands
    description: Push fixes branch to remote
    commands:
      - cd {{vars.repoDir}}
      # FIX APPLIED: Used secret() function instead of envs
      - git push "https://github-token:{{secret('GITHUB_TOKEN')}}@{{inputs.repoUrl | replace('https://', '')}}" {{vars.fixBranch}}

  # Step 8: Create Pull Request
  - id: create_pr
    type: io.kestra.plugin.scripts.shell.Commands
    description: Create pull request with fixes
    commands:
      - |
        curl -X POST {{inputs.backendUrl}}/api/github/create-pr \
          -H "Content-Type: application/json" \
          -d '{
            "repoUrl": "{{inputs.repoUrl}}",
            "head": "{{vars.fixBranch}}",
            "base": "{{inputs.branch}}",
            "title": "🔒 Automated Security Fixes - {{execution.startDate | date('yyyy-MM-dd')}}",
            "body": "## Automated Security Fixes..."
          }' \
          -o pr-result.json
        PR_URL=$(grep -o '"url":"[^"]*"' pr-result.json | cut -d'"' -f4)
        echo "::{\"outputs\": {\"pr_url\": \"$PR_URL\"}}::"

  # Step 9: Notify Backend
  - id: notify_backend
    type: io.kestra.plugin.scripts.shell.Commands
    description: Send completion webhook to backend
    commands:
      - |
        curl -X POST {{inputs.backendUrl}}/api/webhooks/kestra \
          -H "Content-Type: application/json" \
          -d '{
            "executionId": "{{execution.id}}",
            "status": "success",
            "scanId": "{{inputs.scanId}}",
            "outputs": {
              "issuesFound": {{outputs.aggregate_results.total_findings}},
              "issuesFixed": {{outputs.generate_fixes | length}},
              "prUrl": "{{outputs.create_pr.pr_url}}"
            }
          }'

errors:
  - id: error_handler
    type: io.kestra.plugin.scripts.shell.Commands
    description: Handle workflow errors
    commands:
      - |
        curl -X POST {{inputs.backendUrl}}/api/webhooks/kestra \
          -H "Content-Type: application/json" \
          -d '{
            "executionId": "{{execution.id}}",
            "status": "failure",
            "scanId": "{{inputs.scanId}}",
            "error": "Workflow execution failed"
          }'

triggers:
  - id: webhook_trigger
    type: io.kestra.plugin.core.trigger.Webhook
    key: "security-scan-webhook-key"
    description: Webhook trigger for security scans